{% set name = "afni" %}
# {% set version = "18.2.06" %}
# {% set sha256 = "dee033d8435740e844308415f73ce674c60f53ed42a52085bd706b05f2218042" %}

package:
  name: {{ name }}
  version: {{ GIT_DESCRIBE_TAG or '99.99.99'}}

source:
  git_url: ..
  rev: {{ GIT_DESCRIBE_TAG  or "HEAD"}}

  # url:  https://github.com/{{ name }}/{{ name }}/archive/AFNI_{{ version }}.tar.gz
  # sha256: {{ sha256 }}
  # patches:
  #   - makefile.patch
  #   - suma_makefile.patch

build:
  number: 2
  # skip: True # [osx]
  # skip: True # [py3k]

  missing_dso_whitelist:                                         # [osx]
    - /usr/lib/libSystem.B.dylib
    - /usr/local/opt/openmotif/lib/libXm.4.dylib
    - /opt/X11/lib/*



requirements:
  build:
    - {{ compiler('c') }}
    - cmake >=3.13
    - ninja
    - pkg-config
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]





  host:
    - python
    - libpng 1.6
    - jpeg
    - zlib
    - openssl
    - freetype
    - libglu # [linux]
    - freeglut # [linux]
    - expat
    - gsl
    - openmotif-dev # [linux]
    - glib
    - xorg-libxpm # [linux]
    - xorg-libxmu # [linux]
    - xorg-libxi # [linux]
    - xorg-libx11 # [linux]
    - xorg-libxt # [linux]
    - xorg-libxft # [linux]
    - xorg-libxcb # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxext # [linux]
    - mesalib # [linux]
    # - r
    # - r-rmpi
    # - r-afex
    # - r-phia
    # - r-snow
    # - r-nlme
    # - r-lme4
    # - r-paran
    # - r-psych
    # - r-brms
    #- nifti_clib
    #- gifti_clib
    - libnetcdf
    - f2c


  run:
    # - r
    # - r-rmpi
    # - r-afex
    # - r-phia
    # - r-snow
    # - r-nlme
    # - r-lme4
    # - r-paran
    # - r-psych
    # - r-brms
    - tcsh  

test:
  commands:
    - afni --help

about:
  home: https://afni.nimh.nih.gov/afni
  summary: "AFNI is a suite of programs for looking at and analyzing 3D brain images."
  license: GPL-2.0
  license_family: GPL
  license_file: doc/README/README.copyright
  dev_url: https://github.com/afni/afni

extra:
  container:
    extended-base: True
