# {% set version = "18.2.06" %}
# {% set sha256 = "dee033d8435740e844308415f73ce674c60f53ed42a52085bd706b05f2218042" %}
package:
  name: afni-minimal
  version: {{ GIT_DESCRIBE_TAG or '99.99.99'}}

source:
  git_url: ..
  rev: {{ GIT_DESCRIBE_TAG  or "HEAD"}}
  # url:  https://github.com/{{ name }}/{{ name }}/archive/AFNI_{{ version }}.tar.gz
  # sha256: {{ sha256 }}
  # patches:
  #   - makefile.patch
  #   - suma_makefile.patch

build:
  number: 0
  # skip: True # [osx]
  # skip: True # [py3k]

  missing_dso_whitelist:                                         # [osx]
    - /usr/lib/libSystem.B.dylib

requirements:
    build:
      - {{ compiler('c') }}
      - cmake >=3.14.7
      - ninja
      - pkg-config
      - llvm-openmp  # [osx]
      - libgomp      # [linux]
      - python
    host:
      - zlib
      - expat
      - f2c


about:
  home: https://afni.nimh.nih.gov/afni
  summary: "AFNI is a suite of programs for looking at and analyzing 3D brain images."
  license: GPL-2.0
  license_family: GPL
  license_file: doc/README/README.copyright
  dev_url: https://github.com/afni/afni

extra:
  container:
    extended-base: True

