# {% set version = "18.2.06" %}
# {% set sha256 = "dee033d8435740e844308415f73ce674c60f53ed42a52085bd706b05f2218042" %}
package:
  name: afni
  version: {{ GIT_DESCRIBE_TAG or '99.99.99'}}

source:
  git_url: ..
  rev: {{ GIT_DESCRIBE_TAG  or "HEAD"}}
  # url:  https://github.com/{{ name }}/{{ name }}/archive/AFNI_{{ version }}.tar.gz
  # sha256: {{ sha256 }}
  # patches:
  #   - makefile.patch
  #   - suma_makefile.patch

build:
  number: 0
  # skip: True # [osx]
  # skip: True # [py3k]

  missing_dso_whitelist:                                         # [osx]
    - /usr/lib/libSystem.B.dylib
    - /usr/local/opt/openmotif/lib/libXm.4.dylib
    - /opt/X11/lib/*

requirements:
  run:
    - afni-core-libraries
    - afni-core-binaries
    - afni-python
    - afni-tcsh
    - afni-gui
    - afni-suma
    # - afni-rstats

outputs:
  - name: afni-core-libraries
    requirements:
      build:
        - {{ compiler('c') }}
        - cmake >=3.13
        - ninja
        - pkg-config
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
      host:
        - libpng 1.6
        - jpeg
        - zlib
        - openssl
        - freetype
        - expat
        - gsl
        - libnetcdf
        - f2c
        - tcsh
        # - nifti_clib
        # - gifti_clib
      script: conda_build.sh
      script_interpreter: conda_build.sh arg values
  - name: afni-core-binaries
    requirements:
      - afni-core-libraries
  - name: afni-python
    requirements:
      - python
      - matplotlib
  - name: afni-tcsh
    requirements:
      - tcsh
      - afni-core-libraries
      - afni-core-binaries
  - name: afni-gui
    requirements:
      - afni-core-libraries
      - xorg-libxpm # [linux]
      - xorg-libxmu # [linux]
      - xorg-libxi # [linux]
      - xorg-libx11 # [linux]
      - xorg-libxt # [linux]
      - xorg-libxft # [linux]
      - xorg-libxcb # [linux]
      - xorg-libxfixes  # [linux]
      - xorg-libxext # [linux]
      - openmotif-dev # [linux] 
  - name: afni-suma
    requirements:
      - {{ cdt('mesa-libgl-devel') }}  # [linux]
      - {{ cdt('mesa-dri-drivers') }}  # [linux]
      - {{ cdt('libselinux') }}  # [linux]
      - {{ cdt('libxdamage') }}  # [linux]
      - {{ cdt('libxxf86vm') }}  # [linux]
      - afni-gui
      - mesalib # [linux]
      - glib
  # - name: afni-rstats
  #   requirements:
  #     - afni-gui
  #     - afni-core-binaries
  #     - r
  #     - r-rmpi
  #     - r-afex
  #     - r-phia
  #     - r-snow
  #     - r-nlme
  #     - r-lme4
  #     - r-paran
  #     - r-psych
  #     - r-brms


test:
  commands:
    - afni -help

about:
  home: https://afni.nimh.nih.gov/afni
  summary: "AFNI is a suite of programs for looking at and analyzing 3D brain images."
  license: GPL-2.0
  license_family: GPL
  license_file: doc/README/README.copyright
  dev_url: https://github.com/afni/afni

extra:
  container:
    extended-base: True

  # host:
          #   - python
          #   - libpng 1.6
          #   - jpeg
          #   - zlib
          #   - openssl
          #   - freetype
          #   - libglu # [linux]
          #   - freeglut # [linux]
          #   - expat
          #   - gsl
          #   - openmotif-dev # [linux]
          #   - glib
          #   - xorg-libxpm # [linux]
          #   - xorg-libxmu # [linux]
          #   - xorg-libxi # [linux]
          #   - xorg-libx11 # [linux]
          #   - xorg-libxt # [linux]
          #   - xorg-libxft # [linux]
          #   - xorg-libxcb # [linux]
          #   - xorg-libxfixes  # [linux]
          #   - xorg-libxext # [linux]
          #   - mesalib # [linux]
          #   # - r
          #   # - r-rmpi
          #   # - r-afex
          #   # - r-phia
          #   # - r-snow
          #   # - r-nlme
          #   # - r-lme4
          #   # - r-paran
          #   # - r-psych
          #   # - r-brms
          #   #- nifti_clib
          #   #- gifti_clib
          #   - libnetcdf
          #   - f2c



          #   - tcsh  

